# Generated by Django 4.2 on 2024-05-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cardb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(blank=True, max_length=100, null=True)),
                ('Car_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Car_price', models.IntegerField(blank=True, null=True)),
                ('C_Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Car_Image', models.ImageField(blank=True, null=True, upload_to='Car Images')),
            ],
        ),
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
    ]
