# Generated by Django 5.0.6 on 2024-06-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pickup', models.CharField(blank=True, max_length=100, null=True)),
                ('Dropoff', models.CharField(blank=True, max_length=100, null=True)),
                ('Pickup_date', models.IntegerField(blank=True, null=True)),
                ('Dropoff_date', models.IntegerField(blank=True, null=True)),
                ('Pickup_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
