# Generated by Django 5.0.6 on 2024-06-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_bookdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='Dropoff_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookdb',
            name='Pickup_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
