# Generated by Django 5.0.6 on 2024-06-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_bookdb_dropoff_date_alter_bookdb_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='User_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile Images'),
        ),
        migrations.AddField(
            model_name='bookdb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='User_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile Images'),
        ),
    ]
