# Generated by Django 5.0.6 on 2024-06-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_bookdb_user_image_bookdb_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdb',
            name='User_image',
        ),
    ]
