# Generated by Django 5.0.6 on 2024-06-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_bookdb_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='User_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile Images'),
        ),
    ]
